[package]
name = "imap-archive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
native-tls = "0.2.2"
lazy_static = "1.4.0"
anyhow = "1.0.52"
chrono = "0.4.19"
